name: announcement_of_services
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:

  cloud_firestore: ^4.13.2
  crypto: ^3.0.1
  firebase_core: ^2.23.0
  firebase_storage: ^11.6.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  http: ^0.13.6
  image_picker: ^1.0.4
  intl: ^0.18.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  url_launcher: ^6.0.9
  uuid: ^4.2.1

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/images/clients_home_appliance1.png
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/cairo/Cairo-Black.ttf
        - asset: assets/fonts/cairo/Cairo-Bold.ttf
        - asset: assets/fonts/cairo/Cairo-ExtraBold.ttf
        - asset: assets/fonts/cairo/Cairo-ExtraLight.ttf
        - asset: assets/fonts/cairo/Cairo-Light.ttf
        - asset: assets/fonts/cairo/Cairo-Medium.ttf
        - asset: assets/fonts/cairo/Cairo-Regular.ttf
        - asset: assets/fonts/cairo/Cairo-SemiBold.ttf

flutter_intl:
  enabled: true
